### ISSUE TITLE
Genome identifiers

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#179]
Related to #177, #153, #81, #82 

Needs for implementing genome identifiers:

- [x] API point that converts a human identifier to the server's digest for that id
- [x] genome id lives on namespace
- [ ] genome_mask lives on asset
- [x] client must operate on digests instead of human-readable identifiers, as explained in #81
- [x] genomes can be renamed (#177)
- [x] genomes can be aliased (#81)

A lot of the 'initialization' question is satisfied by the hierarchy of assets we now have; so if you pull a child of fasta, which is many assets, you automatically get the right genome identifier. in fact, if you pull *anything*, your genome gets initialized.

But what if someone builds a gtf file, before building a fasta or pulling any other asset? then refgenie is in 'unintialized genome' state, which can be initialized as described in #81 .

## comparing

If you build hg38/fasta and then try to pull hg38/gtf, and genomes are incompatible... refgenie should first check for identical genomes. Upon not finding these, it uses the `genome_mask` in the asset, and compares for any *compatible* genomes. If it finds a correct asset with a compatible genome, it pulls that. If it finds more than one (and they are not identical), it must prompt the user for a more specific genome.
